# Generated by Django 5.1.7 on 2025-05-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('listener', 'Listener'), ('admin', 'Admin')], max_length=10, verbose_name='User Type'),
        ),
    ]
