# Generated by Django 5.1.7 on 2025-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='keywords',
            field=models.TextField(blank=True, help_text='Từ khóa để cải thiện tìm kiếm'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, help_text='Thời gian truy cập gần nhất'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='relevance_score',
            field=models.FloatField(default=1.0, help_text='Điểm liên quan để ưu tiên kết quả'),
        ),
    ]
