# Generated by Django 5.1.7 on 2025-04-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='videos',
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='songs/thumbnails/'),
        ),
        migrations.AddField(
            model_name='song',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/video/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='songs/audio/'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
